// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBHyH7EDIiLobm3hCqqofNOWgZzyytJk',
    appId: '1:558320465748:web:40281638995f51d63afac1',
    messagingSenderId: '558320465748',
    projectId: 'flutter-delight-corner',
    authDomain: 'flutter-delight-corner.firebaseapp.com',
    storageBucket: 'flutter-delight-corner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5v0IY3mXSb0wbkJpnM6r-NAG11QTkROM',
    appId: '1:558320465748:android:db592aba68d9713e3afac1',
    messagingSenderId: '558320465748',
    projectId: 'flutter-delight-corner',
    storageBucket: 'flutter-delight-corner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1JST5z5X2A2_ENqV84nfRv0vya0_L-c',
    appId: '1:558320465748:ios:f06258fd2255e7023afac1',
    messagingSenderId: '558320465748',
    projectId: 'flutter-delight-corner',
    storageBucket: 'flutter-delight-corner.appspot.com',
    iosBundleId: 'com.example.delightCorner',
  );
}
